### ISSUE TITLE
abi version?

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#101]
@marekkokot 
at https://github.com/refresh-bio/KMC/blob/master/makefile#L89
what is the reason for the abi version option?

**Comment by marekkokot** [comment]
Well,

KMC uses vectorclasslib to detect cpu instruction set. vectorclasslib documentation says that under g++ vectroclasslib should be compiled with -fabi-version=0, although I think it was not needed to just detect available instruction set. Nevertheless vectorclasslib dependency was dropped with 4df82be238b00e814efc782c468045d482ec3737 and with 2503a4d02058f7c50386df3934f53350031f1eac this flag was removed. I have also removed -mfma which was probably accidentally added to makefile.
