### ISSUE TITLE
Can not read data downloaded from NCBI

### ISSUE THREAD

**Issue by JasonKwuo** [refresh-bio/KMC#110]
[GCF_002953275.1_ASM295327v1_genomic.fna.gz](https://github.com/refresh-bio/KMC/files/2330408/GCF_002953275.1_ASM295327v1_genomic.fna.gz)

cmd: kmc -ci1 -cs1 -f -fm -k17 .//./GCF_002953275.1_ASM295327v1_genomic.fna.gz ../../result.d/verify.d/GCF_002953275.1_ASM295327v1_genomic.fna.gz ./tmp_data

Error: Some error while reading gzip file

**Comment by marekkokot** [comment]
Hi,
Thanks for reporting that.
88053157bb74fb9d1b39bb90a2994f79a257000c should fix this issue. If something is still wrong please reopen this issue and let me know.
