### ISSUE TITLE
kmc_tools transform histogram cs maximum 10000

### ISSUE THREAD

**Issue by tbenavi1** [refresh-bio/KMC#115]
Whenever I run:

kmc -k21 -m24 -ci1 -cs15000 @FILES OUTPUT tmp/
kmc_tools transform OUTPUT histogram OUTPUT.hist

the OUTPUT.hist file only goes up to 10,000 lines even though I explicitly set cs to be 15000. In fact, it doesn't seem to matter what number I use for cs, it won't go past 10000. Am I doing something wrong? Thanks.

**Comment by marekkokot** [comment]
Hi,

Thanks for using kmc and kmc_tools.
You should use:
```
kmc_tools transform OUTPUT histogram OUTPUT.hist -cx15000
```
It was not properly documented in help of kmc_tools nor in kmc_tools documentation, but it was updated with last commits.
Let me know if it works now.

**Comment by tbenavi1** [comment]
This works. Thanks!
