### ISSUE TITLE
Is it possible to replace kmer counts with another value?

### ISSUE THREAD

**Issue by mladen5000** [refresh-bio/KMC#125]
Hi there, 

I was wondering on the relative difficulty it would be to replace the kmer counts with something like a taxonomic ID instead. Would this be a complicated procedure or is it the code to assign counts localized somewhere that can easily be edited?

**Comment by marekkokot** [comment]
Hi,
well, it depends on how exactly you want to use it. In general, ```KMC``` will always store counts of k-mers, but ```kmc_tools``` may modify them. I think that maybe what you are looking for was discussed in issue #58.
Basically, you may create KMC database for each sample, and using ```kmc_tools set_counts``` replace counters with taxonomy ID. Is that sufficient for you? If no, could you please describe your use case more detailed?

**Comment by mladen5000** [comment]
I think this is exactly what I'm looking for. I wasn't sure from the documentation if kmc_tools could modify them. I will look into it as well as issue #58. Thank you!
