### ISSUE TITLE
OpenForRA method with optional minimum and maximum parameters

### ISSUE THREAD

**Issue by tbenavi1** [refresh-bio/KMC#129]
Hello,

For the OpenForRA method, is it possible to only load those kmers with counters between a certain minimum and maximum counter value?

Unless I am wrong, it seems like the minimum and maximum values can only be set once the entire kmc files are loaded. This however would lead to much more memory being used than necessary. 

Thanks for any assistance.

**Comment by marekkokot** [comment]
Hi,

thanks for using KMC.

you are right. For now, there is no option to filter out k-mers during KMC database loading. 
However, you may filter k-mers first, before even using kmc API by filtering k-mers with kmc_tools.
kmc_tools documentation is [here](https://github.com/refresh-bio/KMC/blob/2c16e4169bb6a30ffb69f4a1b9227753480d51e3/kmc_tools.pdf) (check out page 8, operation group transform, operation reduce.

In general filtering during loading would be probably faster, but I think my advice should be sufficient. If it is not then let me know and we will consider adding filtering during loading.

best,
Marek

**Comment by tbenavi1** [comment]
Yes,

This should work for now! Thank you.
