### ISSUE TITLE
Option for kmc_dump to be sorted by kmer?

### ISSUE THREAD

**Issue by tseemann** [refresh-bio/KMC#131]
I know `kmc_dump kmcdb /dev/stdout | sort -k1,1d > kmers.tsv` works, but would it be more efficient for `kmc_dump` to do it internally?

**Comment by marekkokot** [comment]
Use ```kmc_tools transform kmcdb dump -s kmers.tsv```. kmc_tools documentation is [here](https://github.com/refresh-bio/KMC/blob/master/kmc_tools.pdf), what you need is described on pages 8 and 9. In general, it is recommended to use ```kmc_tools``` instead of ```kmc_dump```.

**Comment by tseemann** [comment]
Nice! I didn't see this option!
```
 For dump operation there are additional oper_params:
  -s - sorted output
```
Thank you.  
I will switch to `kmc_tools` now.

**Comment by lmanchon** [comment]
yes, it works but it is sorted by kmer string not by occurrence.
