### ISSUE TITLE
CS option

### ISSUE THREAD

**Issue by Malabady** [refresh-bio/KMC#136]
Hello:

Could you please explain the function of the CS" option and how its value affect the outcomes of kmc?

CS -- maximal value of a counter

I see people using 15,000 or 10,000 but not sure what's the difference in the outcomes.

Also, do you have specific recommendation for using KMC on long reads data (PacBio and ONT)

Many thanks.
Magdy

**Comment by marekkokot** [comment]
Hello,

sorry for the late response. 
The CS option is used internally to determine how many bytes are required to store the counter of a k-mer.
For example if the value is lower than 256 one byte is sufficient. In the case of 15k and 10k, two bytes will be used. The default is 255 which should be sufficient in most cases. In fact, it depends on your application. When you specify 15k or 10k there will be two bytes used for each k-mer in the database. If you specify -cs10000 and some k-mer occur 12,5k times in your input it will be reported as existing only 10k times. It really depends on what you need and how important the exact count is for frequent k-mers in your application. 

In the matter of long reads I do not have any special recommendations, KMC should handle them, but if you spot any problem I would be really thankful if you report it with details.

If it answers your questions please close this issue.

Thanks for using KMC.
Marek

**Comment by Malabady** [comment]
Thank you, Marek. Yes, this answers my question. Best regards! Magdy
