### ISSUE TITLE
CKMCFile::GetBothStrands -- discrepancy in documentation

### ISSUE THREAD

**Issue by karasikov** [refresh-bio/KMC#139]
Dear developers,

On the [wiki](https://github.com/refresh-bio/KMC/wiki/Python-wrapper-for-KMC-API#ckmcfile-class), GetBothStrands is described as:
`GetBothStrands - returns True if KMC was run with -b switch, False otherwise`.
However, if I check the [source code](https://github.com/refresh-bio/KMC/blob/master/kmc_api/kmc_file.h#L131), it says:
```c++
	//Return true if kmc was run without -b switch.
	bool GetBothStrands(void);
```

Which one is correct?

Thanks!

**Comment by marekkokot** [comment]
Hi,

The wiki was wrong, thanks for pointing out this discrepancy. It is fixed now.
