### ISSUE TITLE
How many kmers in an existing kmc file?

### ISSUE THREAD

**Issue by cmfield** [refresh-bio/KMC#148]
Is it possible to find out how many kmers are in an existing kmc database file (.kmc_pre and .kmc_suf files) without using kmc_dump?

When I perform a set operation with kmc_tools, I really want to know how many kmers I ended up with in the db after it's done..

**Comment by marekkokot** [comment]
Hi,
yes it is possible without performing dump. 
There is a hidden operation in ```kmc_tools``` named ```info```. It prinst the database statistics.
Usage example for a kmc dabaset o.kmc_pre o.kmc_suf:
```
./kmc_tools info o
```

The other possible way is to use KMC API, and class Info method.
Let me know if it helps.
Thanks for using KMC.

**Comment by cmfield** [comment]
Yes! That's perfect thanks.
