### ISSUE TITLE
Error: Wrong input file!

### ISSUE THREAD

**Issue by GuillaumeHolley** [refresh-bio/KMC#15]
Hi there.

I am currently trying to use KMC to count 36-mers in a bench of files I have downloaded from the SRA and for a lot of them, KMC just returns me the following error:
`********Error: Wrong input file!`

An example is the file SRR1047856 from the SRA. On one computer with Ubuntu 15.04, I have downloaded its corresponding SRA file and extracted the FASTA file out of it. Then, I ran the command:
`/home/gholley/KMC/bin/kmc -k36 -ci3 -fa SRR1047856.fasta SRR1047856_comp .`
and obtained in return:
`********Error: Wrong input file!`
I tried different parameters for _k_ and _ci_. I tried limiting the number of threads and the RAM-only mode as well as extracting the FASTQ file from the SRA file instead of the FASTA file. Same error.

I though that my SRA file might have been corrupted during the download so I re-downloaded directly the FASTA file from the SRA on a different computer (with Ubuntu 16.10). My local KMC branch was up to date with this git repository. I tried the same command and I obtained the same error.

Any help with this would be welcome :)
Thank you!

Best, Guillaume.

**Comment by marekkokot** [comment]
Hi,

Thanks for using KMC.

I suppose I know the reason. I gues you are getting theSRR1047856 file using command like:
```
fastq-dump --fasta SRR1047856
```
Resulting file SRR1047856.fasta has sequences in fact in multiline fasta format. Such format is supported by KMC with -fm switch. In this case it would be better to have single line fasta format. According to  [fastq-dump documentation](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump) it may be achieved using command line:
```
fastq-dump --fasta 0 SRR1047856
```
I really recommend single line fasta as KMC is able to handle it faster in a case of that short sequences.

You mentioned that you have tried also FASTQ format. Did you remove -fa swich when running KMC in such case?

I hope it will help, but if not please let me know.

Best

**Comment by GuillaumeHolley** [comment]
Hi there,

thanks for the tip! Indeed, I used _fastq-dump_ as you described but I did not use the -fm switch (but I used the -fq switch for the FASTQ files). Anyway, I am going to extract single line FASTA files if it is faster with KMC. Since I think this was the problem, I close the issue and hopefully, I won't need to reopen it :)

Thanks again!

Best, Guillaume
