### ISSUE TITLE
Ignore N in the reads.

### ISSUE THREAD

**Issue by yeban** [refresh-bio/KMC#16]
I am looking to use KMC to filter rare k-mers pre-assembly and was wondering if there's a way to tell it to ignore `N`s in the reads (which could be uncalled bases or masked low-quality bases). Maybe KMC automatically does that?

**Comment by marekkokot** [comment]
KMC do it automatically. There will be no k-mer containing ```N```, also ```N```s are **not** converted to any valid symbol. For an example read:
```ACGTCTGAGGCATGNGACTTGTGAC```
only such 9-mers will be taken to further processing:
```
ACGTCTGAG
 CGTCTGAGG
  GTCTGAGGC
   TCTGAGGCA
    CTGAGGCAT
     TGAGGCATG      
               GACTTGTGA
                ACTTGTGAC
```

**Comment by yeban** [comment]
That's perfect (and quick!), thanks!
