### ISSUE TITLE
kmc does not write to working_directory 

### ISSUE THREAD

**Issue by eaton-lab** [refresh-bio/KMC#160]
I am on Linux using kmc 3.1.1 installed from `conda install kmc -c bioconda`. No matter what I try kmc seems to always write the database files into my current directory, instead of into the specified working directory. Am I doing something wrong? Any help is appreciated.

An example is below:

```bash
# get test fastq file
wget https://eaton-lab.org/data/40578.fastq.gz

# make a directory where I want the database to be stored
mkdir results

# run kmc telling it to write to the results/ dir
kmc -k21 40578.fastq.gz test results/
```

```bash
# look in results dir
ls results/
```
... nothing here

```bash
# look in current dir
ls
```
```
test.kmc_pre
test.kmc_suf
```
the results are here instead of in the specified working dir.

**Comment by eaton-lab** [comment]
I'll close this because I see that workdir is only for the location of temp files.

**Comment by marekkokot** [comment]
:)
If you want output in results directory use:
```
kmc -k21 40578.fastq.gz results/test results/
```
