### ISSUE TITLE
.bin files missing in tmp dir

### ISSUE THREAD

**Issue by RNieuwenhuis** [refresh-bio/KMC#162]
Hi,

I used the following command using K-Mer Counter (KMC) ver. 3.1.1 (2019-05-19) :

` kmc -t32 -k16 -m380 -ci1 -cs10000 @Fastqc/Files_all.list K_mer_16/K_mer_kmc_db_k_16 K_mer_16/tmp`

And while looking at in the temporary directory I noticed there are gaps in the numbers of the .bin files. Is this correct behavior?

**Comment by marekkokot** [comment]
Hi,

In general, in the second stage of the algorithm files are removed after their content is read. Files are read in more or less random order. So yes, it is possible that there are gaps in the numbers during the second stage of the algorithm.
Thanks for using KMC. in case of any further doubts don't hesitate and ask.

**Comment by RNieuwenhuis** [comment]
Thanks for clarifying and creating/maintaining kmc, it is a great tool!
