### ISSUE TITLE
Producing smaller k-mers from databases with larger k-values

### ISSUE THREAD

**Issue by jamshed** [refresh-bio/KMC#165]
Hello @marekkokot, thanks again for the awesome library! We have been using KMC3 for some research projects in our [lab](https://github.com/COMBINE-lab), like our tool cuttlefish ([manuscript](https://www.biorxiv.org/content/10.1101/2020.10.21.349605v2.full) and [repo](https://github.com/COMBINE-lab/cuttlefish)) and it performs really great for our requirements. A need for a utility that arose lately—and having that would save a _lot_ of computational work—is to produce a `k`-mer database from some existing `(k + x)`-mer database (with `x > 0`).  This is the general objective.

To be more specific of our needs, say that we have built a `(k + 1)`-mer database from some huge amount of input data. We also need all the `k`-mers in our application, which can be produced just the same way. But instead of going over the entire input data _again_, it would be great if there is some procedure to generate the `k`-mers from the already produced `(k + 1)`-mers—saving a lot of computation.

I'm also tagging @rob-p here as both of us are quite curious to have support for this utility. It will be really great if you may have a look into this!

Regards.

**Comment by jamshed** [comment]
Support added in [v3.2.0](https://github.com/refresh-bio/KMC/releases/tag/v3.2.0). Thanks again for the collaboration!

**Comment by marekkokot** [comment]
Thank you as well :-) hoping for a future collab!
