### ISSUE TITLE
Segmentation fault with kmc

### ISSUE THREAD

**Issue by AFrolicOfFerns** [refresh-bio/KMC#174]
Hello,

I have been trying to run kmc on a cluster using: 
`ml -* GCC/10.3.0 KMC/3.1.2rc1-Python-3.9.5`
`ls /path/to/fastq/*_001.fastq.gz > FILES`
`mkdir tmp`
`kmc -v -k16 -t16 -m520 -ci1 -cs10000 @FILES kmcdb tmp` 
and keep getting the following error. The -v output from my run is included at the end of this post. 
My genome is rather large, hence my lowering of the k-mer size to 16. Any idea what's going on here?
Thanks!

> Stage 1: 100%Segmentation fault

> **************************
> 
> ********** Used parameters: **********
> No. of input files           : 1
> Output file name             : kmcdb
> No. of working directories   : 1
> Input format                 : FASTQ
> 
> k-mer length                 : 16
> Max. k-mer length            : 256
> Signature length             : 9
> Min. count threshold         : 1
> Max. count threshold         : 1000000000
> Max. counter value           : 10000
> Both strands                 : true
> RAM only mode                : false
> 
> ******* Stage 1 configuration: *******
> 
> No. of bins                  : 512
> Bin part size                : 65536
> Input buffer size            : 25165824
> 
> No. of readers               : 1
> No. of splitters             : 15
> 
> Max. mem. size               : 520000MB
> Max. mem. per storer         : 387258MB
> Max. mem. for single package :  1512MB
> 
> Max. mem. for PMM (bin parts): 516345MB
> Max. mem. for PMM (FASTQ)    :  2825MB
> Max. mem. for PMM (reads)    :    15MB
> Max. mem. for PMM (b. reader):   805MB

**Comment by marekkokot** [comment]
Hello,

this is not good. My first guess is the amount of memory you are giving KMC. Do you really have 520 GB of RAM available on your machine?
In most cases, KMC does not need such an amount of RAM. 
My first suggestion is to reduce the -m parameter.
In our experiments, KMC was able to count 28-mers in human genome sequencing data of gzipped size 614GB (>736 Gbases) in only 33GB of RAM.
If reducing -m does not help let me know how big is your input and if it is publically available. I would like to reproduce this behavior in our environment.

Best,
Marek

**Comment by AFrolicOfFerns** [comment]
Hi Marek,

Yes, I'm on a cluster at my university. I've got it working now - seems like KMC was not loading properly. I switched to loading it as `module purge; ml GCC/10.3.0 KMC/3.1.2rc1-Python-3.9.5` and it finished without issue.

Thanks for such a quick response!
