### ISSUE TITLE
Missing k-mer bug

### ISSUE THREAD

**Issue by jamshed** [refresh-bio/KMC#180]
Hello @marekkokot, reporting another bug!

I'm using the latest commit 13b9b04120e902d158bd0cb87d83b63b742781b9. Consider the following specific FASTA file:
```
>palindrome
AACTGACATGTCAGTT
```

Executing the following two commands produce the k-mers given below.

```bash
kmc -v -k5 -fa -ci1 -t1 palindrome.fa bug-report.kmc .
kmc_dump bug-report.kmc /dev/stdout
```

```
AACTG	2
ACATG	2
ACTGA	2
ATGTC	2
CTGAC	2
AGACA	2
```

Note that, the canonical k-mer `TGACA` is missing in the output, that corresponds to two k-mer instances from the input—`TGACA` and `TGTCA`. Besides, in the output, there is a canonical k-mer `AGACA` reported to be present twice, which has none of its two instances (`AGACA` and `TGTCT`) present in the input.

**Comment by marekkokot** [comment]
Thank you for reporting this issue!
It has been fixed with a68b0c9d878e720376b4f9848aa362ecace1fdab
