### ISSUE TITLE
How to get gzipped output from kmc_tools filter?

### ISSUE THREAD

**Issue by yeban** [refresh-bio/KMC#20]
I was expecting it would write gzipped out when it took gzipped input, but that doesn't seem to be the case. Is there a switch to turn on gzipped output?

**Comment by yeban** [comment]
Never mind. This seems to work:

    kmc_tools filter -hm 31-mers inp.fq -ci3 /dev/stdout | gzip > out.fq

**Comment by marekkokot** [comment]
Hi, this is what I was about to suggest :)

BTW. Do you need to original ordering of reads to be preserved in the output file? If yes let me know, because for now KMC tools do NOT preserve original ordering, but I may consider adding support for that if needed.

**Comment by yeban** [comment]
That would be great, actually. I am using kmc on paired-end reads, and it's a lot of work restoring order afterwards.

**Comment by yannickwurm** [comment]
Hi @marekkokot , even for single-end reads, conserved order is very handy 
 - e.g. can be helpful for gzip compression if similar reads are next to each other (and this may have been done before input to KMC
 - but can also be helpful for positional filtering.

**Comment by marekkokot** [comment]
Hi, 
Thanks for a feedback. I will try to implement it as soon as possible, yet it is not as simple as adding support for hard masking. For now I may adivce ugly workaround i.e. running KMC tools with one thread, e.g.
```kmc_tools -t1 filter ...```

**Comment by yeban** [comment]
Thanks for the tip, @marekkokot. Saved me a lot of effort.
