### ISSUE TITLE
how to install kmc on arm platform ，the compiled KMC binary will not be used on ARM

### ISSUE THREAD

**Issue by 123xyl** [refresh-bio/KMC#209]
![image](https://user-images.githubusercontent.com/96686347/221091947-54b6af2e-8cc6-4da5-9199-a7d200e82013.png)

**Comment by marekkokot** [comment]
Hi, adding ARM support is a work in progress.

**Comment by marekkokot** [comment]
Hi, this is now added. In case of any troubles reopen this and please give me details.
