### ISSUE TITLE
When compiling make on the arm platform, the following error occurs, using the clang and clang++ compilers

### ISSUE THREAD

**Issue by 123xyl** [refresh-bio/KMC#212]
![image](https://user-images.githubusercontent.com/96686347/224305751-8ebdb78d-46d5-4f15-9835-29310e8577db.png)
When compiling make on the arm platform, the following error occurs, using the clang and clang++ compilers

**Comment by marekkokot** [comment]
Hi,

you need to 
```
git clone --recurse-submodules https://github.com/refresh-bio/kmc.git
```
or

```
git clone https://github.com/refresh-bio/kmc.git
git submodule init
git submodule update
```
not sure if clang will work, officially we require g++ (on mac may be installed with brew)

**Comment by 123xyl** [comment]
![image](https://user-images.githubusercontent.com/96686347/224308120-f73cd495-c12b-4081-96fd-d2be73379c4d.png)

**Comment by marekkokot** [comment]
Hi,

can you give me output of
```
g++ --version
```
?

**Comment by 123xyl** [comment]
![image](https://user-images.githubusercontent.com/96686347/224308894-6584967b-6ff0-4456-a732-fdd09b23e545.png)

**Comment by marekkokot** [comment]
Hi,

hmm that is interesting. 
I have g++-11 installed on M1 MAC OS and it compiles.
How did you install g++-7? In my case `brew` does not allow it with `gcc@7: The x86_64 architecture is required for this software`
Is there a reason why you cannot use precompiled binary from the release page?

**Comment by 123xyl** [comment]
I am installing kmc on a linux arm machine and the compiled binary does not run on arm, it reports an error

**Comment by marekkokot** [comment]
Ohh, I see. And what is the error message? I really appreciate this report.

**Comment by 123xyl** [comment]
![image](https://user-images.githubusercontent.com/96686347/224321283-ad27ccbc-db71-4b31-8b43-9d9696e72d9a.png)

**Comment by marekkokot** [comment]
Are you sure you use the correct release? You should use this:
![image](https://user-images.githubusercontent.com/9378882/224321586-faedc81f-3f95-49b0-a72e-aa6740e70274.png)

**Comment by 123xyl** [comment]
no   i  used the version of 3.2.1

**Comment by 123xyl** [comment]
sorry  i have a try soon

**Comment by marekkokot** [comment]
great. please let me know. We currently have very limited access to Linux arm and we are unable to perform exhaustive testing.

**Comment by 123xyl** [comment]
![image](https://user-images.githubusercontent.com/96686347/224323358-c7cf7569-f80c-4a60-b7fc-91ac7b40bf80.png)

**Comment by marekkokot** [comment]
Thanks :( Not good. 
And updating the compiler is not an option?
Out of curiosity what is your CPU model?

**Comment by 123xyl** [comment]
![image](https://user-images.githubusercontent.com/96686347/224326033-a6ba5b83-68f5-4bff-928c-64e7f85c9d19.png)
![image](https://user-images.githubusercontent.com/96686347/224326080-ac734016-88c4-4770-9371-d3f1d5dfe372.png)
![image](https://user-images.githubusercontent.com/96686347/224326188-9f84003a-af84-4cdf-ac8b-9c15563579f6.png)

**Comment by marekkokot** [comment]
I have used some other flags for compilation and linking, could you please try it this works:
[KMC3.2.2.linux.arm64-static.tar.gz](https://github.com/refresh-bio/KMC/files/10942660/KMC3.2.2.linux.arm64-static.tar.gz)

**Comment by 123xyl** [comment]
ok

**Comment by 123xyl** [comment]
> 
Can you release the compiled binary package now that it is running on arm?

**Comment by marekkokot** [comment]
So, does it mean, the attached [KMC3.2.2.linux.arm64-static.tar.gz](https://github.com/refresh-bio/KMC/files/10942660/KMC3.2.2.linux.arm64-static.tar.gz) works fine on your Linux?

**Comment by 123xyl** [comment]
yes

**Comment by marekkokot** [comment]
Great, thanks. I have replaced the release tarball. I will close this issue now, if something is wrong please let me know and reopen it.
