### ISSUE TITLE
bug: kmc_dump -ci and -cx inclusive/exclusive

### ISSUE THREAD

**Issue by nathanhaigh** [refresh-bio/KMC#23]
The help for `kmc_dump` states that `-ci` excluded kmers occurring less than the specified number of time and `-cx` excludes kmers occurring more than the specified number of times. So to get the kmers which occur exactly 10 times I should be able to specify `-ci10 -cx10`. However, this returns nothing.

If I specify  `-ci10 -cx11`, as expected I get a list of kmers occurring 10 or 11 times.

**Comment by marekkokot** [comment]
Thanks for reporting that bug.
BTW. The recommended way of producing dump is to use KMC tools, e.g.:
```./kmc_tools transform kmers -ci10 -cx10 dump kmers.txt```
It has some adventages over kmc_dump:
 * it is a little faster
 * it is possible to produce sorted list with ```-s``` switch

**Comment by nathanhaigh** [comment]
The reason I haven't used `kmc_tools` is that it generates reporting text on `STDOUT`. This means that I am unable to output the dump to STDOUT and process it in a pipeline to avoid the IO overhead of writing and reading the kmer frequencies. I would like to have done:

```bash
$ kmc_tools transform my_kmer_db -ci4 dump /dev/stdout | head
in1: 0% AAAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAAATTATTTTAGTAACCCTAGT 10
AAAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAATTATTTTAGTAAACCCTAGT 12
AAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAAATTATTTTAGTAACCCTAGTT 10
AAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAATTATTTTAGTAAACCCTAGTT 11
AAAAAAAAACCCTAGTCATTTTATCCTAACCTAACGCAGTCGTTAGCTTCGATCCAAAATCCCCTATTGTT 15
AAAAAAAAACGTCCATGACCATTGGTCGTCTAACAGCCACACTGGTAGCTAGTCTTGTACTCCATGCAAAT 16
AAAAAAAAACTAGGAAAAAAATAGACCACAAACAGAGTGGACATCAACTTAGATGTGACATAACTATGTCA 11
AAAAAAAAACTAGGACAAAAAAATAGACCACAAACAGAGTGGACATCAACTTAGATGTGACATAACTATGT 11
AAAAAAAAACTAGGGTTTCGTAGTAGCAATCTTCGCACTCCGGAAATTCTACCGAGGCAAACAATAACTAT 12
AAAAAAAAAGAAAAGAAAAGGTTAGCTACAGACGTGTGATGAATCAAGTGCTTGAGCTAGTTAGCTTTGTT 12
```

As you can see, the progress is generated on `STDOUT` thus making pipelining undoable. Any chance you could send reporting to `STDERR` instead? Happy to create another issue with this if it helps track the issue.

**Comment by marekkokot** [comment]
You may use:
```$ kmc_tools transform my_kmer_db -ci4 dump /dev/stderr 2>&1 > /dev/null |  head```
But kmc_tools has also an option to hide progress (-hp):
```$ kmc_tools -hp transform my_kmer_db -ci4 dump /dev/stdout | head```

Let me know if it helps. If you still prefer progress to be displayed on STDERR you may open an issue or just let me know here.

**Comment by nathanhaigh** [comment]
Yes, that helps - thanks.

I've opened an issue since reporting errors/progress is, in Linux, conventionally done on `STDERR`. That means that the current behaviour is somewhat unconventional and unexpected from a user perspective.
