### ISSUE TITLE
Progress/warnings to STDERR

### ISSUE THREAD

**Issue by nathanhaigh** [refresh-bio/KMC#24]
Could `KMC` progress/warnings/errors be sent to `STDERR` instead of `STDOUT`. This would then mean that `KMC` follows Linux conventions and makes pipelining `KMC` commands easier and more intuative.

# Current Behaviour

`kmc_tools` sends progress to `STDOUT`:

```bash
$ kmc_tools transform my_kmer_db -ci4 dump /dev/stdout | head
in1: 0% AAAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAAATTATTTTAGTAACCCTAGT 10
AAAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAATTATTTTAGTAAACCCTAGT 12
AAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAAATTATTTTAGTAACCCTAGTT 10
AAAAAAAAAATGATGGGCATTTTAGAAGGGCATTTCAGGTTCATTGAAAATTATTTTAGTAAACCCTAGTT 11
AAAAAAAAACCCTAGTCATTTTATCCTAACCTAACGCAGTCGTTAGCTTCGATCCAAAATCCCCTATTGTT 15
AAAAAAAAACGTCCATGACCATTGGTCGTCTAACAGCCACACTGGTAGCTAGTCTTGTACTCCATGCAAAT 16
AAAAAAAAACTAGGAAAAAAATAGACCACAAACAGAGTGGACATCAACTTAGATGTGACATAACTATGTCA 11
AAAAAAAAACTAGGACAAAAAAATAGACCACAAACAGAGTGGACATCAACTTAGATGTGACATAACTATGT 11
AAAAAAAAACTAGGGTTTCGTAGTAGCAATCTTCGCACTCCGGAAATTCTACCGAGGCAAACAATAACTAT 12
AAAAAAAAAGAAAAGAAAAGGTTAGCTACAGACGTGTGATGAATCAAGTGCTTGAGCTAGTTAGCTTTGTT 12
```

This means that to put `kmc_tools` into a pipeline, you need to either

  * Do some funcky redirection trickery:
```bash
$ kmc_tools transform my_kmer_db -ci4 dump /dev/stderr 2>&1 > /dev/null | head
```
  * Ask `kmc_tools` to not report progress:
```bash
$ kmc_tools -hp transform my_kmer_db -ci4 dump /dev/stdout | head
```

# Desired/Conventional Behaviour

In Linux it is convention to send progress/warnings/errors to `STDERR` and have results etc sent to `STDOUT`. This is so that the expected output of a command can be easily piped into another command (assuming no seeking is required). This is very powerful and can be used to avoid disk IO.

Therefore a change to sending progress/errors/warnings to `STDERR` would allow a more simplified approach to pipelining `KMC` commands:

```bash
kmc_tools transform my_kmer_db -ci4 dump /dev/stdout  2>progress.log | head
```

Issue #23 was where this was originally raised.

**Comment by marekkokot** [comment]
Thanks for suggestion and sorry for the long time it takes.
BTW. It was very good described issue.
