### ISSUE TITLE
New point release (3.0.2).

### ISSUE THREAD

**Issue by yeban** [refresh-bio/KMC#25]
Hi, I was wondering if we have a point release incorporating the recent updates. The version on our uni's compute cluster won't be updated otherwise (policy) and several of us here are dependent on the new masking feature in kmc_tools.

**Comment by tseemann** [comment]
I agree. We need this to upgrade conda and brew pkg systems.

**Comment by marekkokot** [comment]
Now there is a 3.1.0 release. I hoped I will be able to implement some features/improvements faster and than create a release (in fact, now most of them is not ready yet). I think I will create releases more often now, especially on requests like this. Anyway sorry for the long time it took.
