### ISSUE TITLE
Using kmc_file.h from v3.0.1

### ISSUE THREAD

**Issue by gkarthik** [refresh-bio/KMC#27]
I'm trying to use the C++ API but when I include kmc_file.h and compile, I get the following compilation error. 

Compile command 

`g++ read_db.cpp -o read_db`

```
#include <iostream>
#include "../KMC-3.0.1/kmc_api/kmc_file.h"

int main(){
  CKMCFile kmer_database;
  return 0;
}
```

Error, 
```
Compilation started at Thu Apr 13 13:59:49

g++ read_kmc.cpp -o read_kmc
In file included from read_kmc.cpp:2:
In file included from ./../KMC-3.0.1/kmc_api/kmc_file.h:14:
./../KMC-3.0.1/kmc_api/kmer_defs.h:36:11: fatal error: 'ext/algorithm' file not found
        #include <ext/algorithm>
                 ^
1 error generated.

Compilation exited abnormally with code 1 at Thu Apr 13 13:59:49
```

gcc version 6.3.0
OSX El Capitan 10.11.6

**Comment by marekkokot** [comment]
Hi,

For mac you should use makefile_mac.
```
make -f makefile_mac
```
From your warnings I assume you are using clang not g++, please refer #21

**Comment by gkarthik** [comment]
I noticed that right after I posted the issue. It's working my mac. I've been trying to install it on Linux too with no luck.

**Comment by marekkokot** [comment]
What's the problem on Linux?

**Comment by gkarthik** [comment]
I updated the issue. I figured out the installation. Now I get this compilation error when I try using the C++ API (kmc_file.h).

**Comment by marekkokot** [comment]
Could you please try to compile with:
-stdlib=libstdc++
You may also try other flags that are present in ```makefile_mac```
Currently I have no access to MAC OS so I cannot check this by myself.

**Comment by gkarthik** [comment]
I get the following error after using -stdlib=libstdc++
```
g++ -stdlib=libstdc++ -std=c++11 read_kmc.cpp -o read_kmc
In file included from read_kmc.cpp:2:
./KMC-3.0.1/kmc_api/kmc_file.h:90:41: error: no member named 'tuple' in namespace 'std'
        using super_kmers_t = std::vector<std::tuple<uint32, uint32, uint32>>;//start_pos, len, bin_no
                                          ~~~~~^
./KMC-3.0.1/kmc_api/kmc_file.h:90:47: error: unexpected type name 'uint32': expected expression
        using super_kmers_t = std::vector<std::tuple<uint32, uint32, uint32>>;//start_pos, len, bin_no
                                                     ^
./KMC-3.0.1/kmc_api/kmc_file.h:91:58: error: unknown type name 'super_kmers_t'
        void GetSuperKmers(const std::string& transformed_read, super_kmers_t& super_kmers);
                                                                ^
3 errors generated.
```

**Comment by gkarthik** [comment]
In order to use C++11 features I added -stdlib=libc++ to the compile flags and the previous error disappeared but there is a new one. 

g++ -std=c++11 -stdlib=libc++ read_kmc.cpp -o read_kmc

```
In file included from read_kmc.cpp:3:
In file included from ./KMC-3.0.1/kmc_api/kmc_file.h:14:
./KMC-3.0.1/kmc_api/kmer_defs.h:36:11: fatal error: 'ext/algorithm' file not found
        #include <ext/algorithm>
                 ^
1 error generated.

```

**Comment by marekkokot** [comment]
Hi,
I finally have access to MAC and compliled your code with following command:
```
/usr/local/gcc-6.3.0/bin/g++ -std=c++11 ../KMC-3.0.1/kmc_api/*.cpp read_db.cpp -o read_db
```
Could you try this (remember replace g++ path to yours).

**Comment by gkarthik** [comment]
That worked! Thanks!
