### ISSUE TITLE
avx2 detection broken.

### ISSUE THREAD

**Issue by EricDeveaud** [refresh-bio/KMC#31]
hello trying to compile KMC-3.0.1 I have some avx2 related errors.
same kind of error as mentioned in #17 

rapid diggind in the code shows that avx2 is enabled on xeon proc 
but some xeon does not provides avx2 support.

see for example an example of my /proc/cpuinfo 
(running a docker on mac)
```
processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
stepping        : 4
cpu MHz         : 3699.593
cache size      : 10240 KB
physical id     : 5
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 cx16 xtpr pcid dca sse4_1 sse4_2 popcnt aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase erms xsaveopt arat
bugs            :
bogomips        : 7570.22
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by marekkokot** [comment]
Hello,

Thanks for reporting that issue.
Our sorting subroutine is compiled in many versions (SSE2, SSE41, AVX, AVX2). It should compile even if your machine do not support it. The proper version is determined at a runtime depending on what processor supports. Even if there is a xeon we still chech if it supports avx2 and if not we still choose proper version of sorting subroutine.

I suspect the problem is your compiler or assembler. 
What is your g++ version and as version?

My configuration:
```
g++ --version
g++ (Debian 4.9.3-14) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


as --version
GNU assembler (GNU Binutils for Debian) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
```


Could you place full compilation log here?

**Comment by EricDeveaud** [comment]
gcc : 4.9.0
as : 2.20.51

```
gensoft@698917c9feff inst]$ gcc --version 
gcc (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[gensoft@698917c9feff inst]$ as --version
GNU assembler version 2.20.51.0.2-5.44.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
```

**Comment by marekkokot** [comment]
Hi,

I suspect the as version is the reason. Unfortunatelly I was not able to install your version of as. 
Here are all versions of as:
http://ftp.gnu.org/gnu/binutils/

as you may note your version is quite old, so it is possible it does not support avx2 instructions.
Could you install newer version of as?
Alternatively I may create new release with statically compiled KMC.
I will also consider modifing sources to allow compile without AVX2 instructions.
Let me know what you prefer. Thanks.
