### ISSUE TITLE
Option to NOT keep .kmc_pre and .kmc_suf outputs

### ISSUE THREAD

**Issue by tseemann** [refresh-bio/KMC#37]
Running KMC produces two output files: `XXX.kmc_pre` and `XXX.kmc_suf`.

Could you please add an option to **not** create/write or keep these files?

For example, often we only want the summary `Stats:`.

**Comment by marekkokot** [comment]
Hi,

-w switch (without output) was added. 
Please keep in mind that output path still needs to be specified (though it is not used).

**Comment by tseemann** [comment]
Thanks!
