### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by wenjiexiaomeng** [refresh-bio/KMC#39]
Hi,
I tried to install KMC ,but there are some problems occured when I used the command "make DISABLE_ASMLIB=true" and I don't know how to solve this, could you give me some advice? 
Best,
############################################################################
 >>> make DISABLE_ASMLIB=true
g++ -Wall -O3 -m64 -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++11  -DDISABLE_ASMLIB -mavx2 -mfma -fabi-version=0 -c kmer_counter/raduls_avx2.cpp -o kmer_counter/raduls_avx2.o
/tmp/cckJQjTJ.s: Assembler messages:
/tmp/cckJQjTJ.s:27711: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:27714: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rcx)'
/tmp/cckJQjTJ.s:27716: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:27718: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rcx)'
/tmp/cckJQjTJ.s:27823: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:27829: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:27831: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:27833: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:36827: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:36829: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx)'
/tmp/cckJQjTJ.s:36900: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:36902: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:41669: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:41670: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:41672: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:42925: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:42926: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:42928: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:46028: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:46031: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:46033: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:46035: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:46852: Error: no such instruction: `vinserti128 $0x1,%xmm2,%ymm3,%ymm2'
/tmp/cckJQjTJ.s:46853: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:46855: Error: no such instruction: `vextracti128 $0x1,%ymm2,16(%rax)'
/tmp/cckJQjTJ.s:46857: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:46913: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:46919: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:46921: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:46923: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:47314: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:47315: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:47317: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:48587: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:48588: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:48590: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:50550: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:52688: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:52689: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:52691: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:53960: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:53961: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:53963: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:57720: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:57721: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:57723: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:58988: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:58989: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:58991: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:62058: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:62059: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:62061: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:63323: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:63324: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:63326: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:65465: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:65467: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:66050: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:66052: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:66091: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'
/tmp/cckJQjTJ.s:66093: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:66451: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:66452: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:66454: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:67714: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:67715: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:67717: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:70575: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:70576: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:70578: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:71836: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:71837: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:71839: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:73822: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:73823: Error: suffix or operands invalid for `vpaddq'
/tmp/cckJQjTJ.s:73825: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:75091: Error: no such instruction: `vinserti128 $0x1,16(%rdx,%rax),%ymm0,%ymm0'
/tmp/cckJQjTJ.s:75092: Error: suffix or operands invalid for `vpaddd'
/tmp/cckJQjTJ.s:75094: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx,%rax)'
/tmp/cckJQjTJ.s:81696: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:81698: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:81760: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:81762: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:81832: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:81834: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rdx)'
/tmp/cckJQjTJ.s:81909: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:81911: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:83185: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:83187: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:83249: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:83251: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:83323: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:83325: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rsi)'
/tmp/cckJQjTJ.s:83399: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:83401: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:93800: Error: no such instruction: `vinserti128 $0x1,%xmm2,%ymm3,%ymm2'
/tmp/cckJQjTJ.s:93801: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:93803: Error: no such instruction: `vextracti128 $0x1,%ymm2,16(%rax)'
/tmp/cckJQjTJ.s:93805: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:93896: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:93902: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:93904: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:93906: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:94006: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:94009: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rcx)'
/tmp/cckJQjTJ.s:94011: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:94013: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rcx)'
/tmp/cckJQjTJ.s:94117: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:94123: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:94125: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:94127: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:95555: Error: no such instruction: `vinserti128 $0x1,%xmm2,%ymm3,%ymm2'
/tmp/cckJQjTJ.s:95556: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95558: Error: no such instruction: `vextracti128 $0x1,%ymm2,16(%rax)'
/tmp/cckJQjTJ.s:95560: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:95650: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95656: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:95658: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95660: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
/tmp/cckJQjTJ.s:95763: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95766: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rcx)'
/tmp/cckJQjTJ.s:95768: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95770: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rcx)'
/tmp/cckJQjTJ.s:95872: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95878: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'
/tmp/cckJQjTJ.s:95880: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/cckJQjTJ.s:95882: Error: no such instruction: `vextracti128 $0x1,%ymm0,48(%rax)'
make: *** [kmer_counter/raduls_avx2.o] Error 1

**Comment by marekkokot** [comment]
Hi, 

What is your g++ and as version? Please read also #31 for details.

**Comment by wenjiexiaomeng** [comment]
Hi,
Here is my g++ and as version:
gcc version 5.2.0 (GCC)
as --version: 2.20.51.0.2-5.46.el6

I guess maybe the as version is old.
I will try again, Thanks a lot ~

Best,
Wenjie

**Comment by marekkokot** [comment]
Hi,
Thanks.
Please let me know if you succeeded to solve this with newer version of as. 

Best,
Marek

**Comment by wenjiexiaomeng** [comment]
Hi,
When I tried to undate the new version binutils, some other problems occured...
So I turned to my classmate, and he help me with the conda (bioconda) source? ..sorry I just knew a little with this..finally I can use your great tools now.
Thanks a lot.

Best,
Wenjie

**Comment by marekkokot** [comment]
Hi,

I'm glad that in some way you were able to install KMC. 
Just out of curosity I installed Scientific Linux with as 2.20, and installing new as version did help, so for sure the it was the reason.

I don't know if bioconda version of KMC is up to date, so if you want to compile KMC in the newest version you may report what other problems occurred, and I will try to help.

In that case please report here and reopen this issue, or create new one. For now I am closing this issue.

Anyway, thanks for using our software :)
