### ISSUE TITLE
Extend the length of supported reads in fastq and fasta format

### ISSUE THREAD

**Issue by marekkokot** [refresh-bio/KMC#40]
Bug reported by mail:

> Is there a limit to the length of sequences in a fasta file for the 'kmc' command?

> I run this command
   ` kmc -k25 -ci1 -fa input/test.fasta output/test.res work`

> When the fasta file contains one sequence of 50,000 'A's, the program completes.
> When the fasta file contains one sequence of 60,000 'A's, the programs halts with the message 'Error: Wrong input file!'.
> 
> So, I conclude that sequence lengths have a limit between 50,000 and 60,000 characters. Is that correct?

The limit is not strict (it depents on couple of factors, yet it is enough for short reads)

The workaround in reported case is to use -fm (multifasta format), but in general long reads should be also supported in fasta and fastq format.

**Comment by conchoecia** [comment]
I encountered the same error when running ONT reads through KMC. It worked when I used the `-fm` flag.
