### ISSUE TITLE
asmlib/vectorclass: Licensing issues and clarification

### ISSUE THREAD

**Issue by mbargull** [refresh-bio/KMC#44]
[DISCLAIMER: I am not a lawyer and the following are only my interpretations of the licensing terms -- hence no legal advice but only well-intended suggestions/remarks.]

The [README.md](https://github.com/refresh-bio/KMC/blob/v3.0.1/README.md) states that
> KMC software distributed under GNU GPL 2 licence.

yet it uses `asmlib` (optionally) and `vectorclass` which are both GPL-3.0+ licensed.
Sadly GPL-2.0 and GPL-3.0 are not compatible, see
https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility.
**Hence, to use `vectorclass`, KMC would have to be made available via GPLv3, i.e., licensed under one of GPL-2.0+, GPL-3.0, or GPL-3.0+.**

Furthermore I also find the following from KMC's readme problematic/misleading:
> Note: asmlib is free only for non commercial purposes. If needed, you can contact the author of asmlib or compile KMC without asmlib.

> Note: for commercial usage of asmlib follow the instructions in 'License conditions' (http://www.agner.org/optimize/asmlib-instructions.pdf) or compile KMC without asmlib. In case of doubt, please consult the original documentations.

> vcl is under the licence GNU GPL 3 or higher Node: for commercial usage of vcl follow the instructions in 'License' section (http://www.agner.org/optimize/vectorclass.pdf)

But as `asmlib`/`vectorclass` can be used in terms of the GPL-3.0, no restrictions concerning commercial/non-commercial usage should be applicable, see
https://www.gnu.org/licenses/gpl-faq.html#NoMilitary
and
https://www.gnu.org/licenses/gpl.html#section7.
(IMO, the use of the sole term "Commercial licenses" from the `asmlib` and `vectorclass` license texts is also misleading, as they (to me) kind of suggest the interpretation GPL=free=non-commercial which is wrong. "Alternative custom/proprietary/??? license" might have been a better choice...)

----
Just for reference/context the license information for `asmlib` and `vectorclass`:

From http://www.agner.org/optimize/asmlib-instructions.pdf:
>10 License conditions
>
>These software libraries are free: you can redistribute the software and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation, either version 3 of the license, or any later version.
>
>Commercial licenses are available on request to www.agner.org/contact.
>
>This software is distributed in the hope that it will be useful, but without any warranty. See 
the file license.txt or www.gnu.org/licenses for the license text.

From http://www.agner.org/optimize/vectorclass.pdf:
>License
>
>The VCL vector class library has a dual license system. You can use it for free in 
open source software, or pay for using it in proprietary software.
>
>You are free to copy, use, redistribute and modify this software under the terms of
the GNU General Public License as published by the Free Software Foundation, 
version 3 or any later version. See the file license.txt.
>
>Commercial licenses are available on request.

**Comment by marekkokot** [comment]
Hi,

Thanks for reporting that. We will consider this. In fact, we plan to drop vectorclasslib dependency and check if we can easily drop also asmlib dependency. I would like to say we will do this quickly, sadly I cannot promise that. 

BTW. Thanks for using KMC and working on integrating it into bioconda. 
I think this issue is really nicely written.

**Comment by mbargull** [comment]
Thank you for you kind reply and for looking into this!

**Comment by marekkokot** [comment]
I think its time to close this issue as both asmlib and vcl  dependencies was droped with 4df82be238b00e814efc782c468045d482ec3737 and c026093b269fefe5bee56eee907810ab3a674624.
