### ISSUE TITLE
kmer counts incorrect?

### ISSUE THREAD

**Issue by hmusta** [refresh-bio/KMC#46]
I've been testing out KMC with the following dummy sequence
```
>dummy
AATGGGTCCCTGTTTCGCGATAAAATGCCAATCGCTCTAAATATCGCGCTAGC
```
with the command `kmc -ci0 -fm -k3 -cs300 dummy_genome.fa dummy_kmc kmc_temp`

The result is
```
Stage 1: 100%
1st stage: 0.002018s
2nd stage: 0.001863s
Total    : 0.003881s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :           25
   No. of unique counted k-mers       :           25
   Total no. of k-mers                :           51
   Total no. of sequences             :            1
   Total no. of super-k-mers          :            0
```
while the sequence actually has 33 unique 3-mers.

I'm compiling with gcc 6.3.0. Maybe I'm doing something wrong...

**Comment by marekkokot** [comment]
Hi,

Thanks for using KMC!

In most applications, k-mer and its reverse complement should not be distinguished. 
Simply speaking for each k-mer its [reverse complement](http://bioweb.uwlax.edu/GenWeb/Molecular/Seq_Anal/Reverse_Comp/reverse_comp.html) is calculated.
Canonical k-mer is a lexicographically slammer of two (k-mer and its reverse complement). KMC in default mode counts only canonical k-mers. 

If you need k-mers as they are, there is an **-b** option. Then for you sequence the output is:
```
Stage 1: 100%
1st stage: 0.0552348s
2nd stage: 0.0376972s
Total    : 0.092932s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :           34
   No. of unique counted k-mers       :           34
   Total no. of k-mers                :           51
   Total no. of sequences             :            1
   Total no. of super-k-mers          :            0
```

There are in fact 34 k-mers:
```
AAA	3
AAT	4
AGC	1
ATA	2
ATC	2
ATG	2
CAA	1
CCA	1
CCC	1
CCT	1
CGA	1
CGC	4
CTA	2
CTC	1
CTG	1
GAT	1
GCC	1
GCG	2
GCT	2
GGG	1
GGT	1
GTC	1
GTT	1
TAA	2
TAG	1
TAT	1
TCC	1
TCG	3
TCT	1
TGC	1
TGG	1
TGT	1
TTC	1
TTT	1
```

If you agree and have no questions please close this issue, in the opposite case let me know what is not clear.

**Comment by hmusta** [comment]
Yes, that clears things up. Thanks!
