### ISSUE TITLE
v3.0.1 is still printing "v3.0.0" in the help?

### ISSUE THREAD

**Issue by tseemann** [refresh-bio/KMC#52]
```
K-Mer Counter (KMC) ver. 3.0.0 (2017-01-28)
```

https://github.com/marekkokot/KMC/archive/v3.0.1.tar.gz

I think you have fixed it in github `KMC_VER` but haven't made a new release.
Which will be 3.0.2 then :-)

**Comment by marekkokot** [comment]
I am closing this issue for the same reason I closed #25
