### ISSUE TITLE
the 'complex' operation of kmc_tools does not seem to work

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#54]
The example in the manual gives "terminate called after throwing an instance of std::regex_error"
Same error for other examples I've tried.   What would be the simplest example of the operations file that should work? @marekkokot

**Comment by marekkokot** [comment]
Hi,

Here is some simple example. 
Lets suppose three simple fasta files:
in1.fasta:
```
>
AAAAAAAAAAAAAAAAAAAA
>
AAAAAAAAAAAAAAAAAAAC

```
in2.fasta:
```
>
AAAAAAAAAAAAAAAAAAAA
>
AAAAAAAAAAAAAAAAAAAA
>
AAAAAAAAAAAAAAAAAAAA
>
AAAAAAAAAAAAAAAAAAAG

```
in3.fasta:
```
>
AAAAAAAAAAAAAAAAAAAA
>
AAAAAAAAAAAAAAAAAAAA

```

**Step 1.** Count k-mers (k=20):
```
./kmc -k20 -fa -ci1 in1.fasta kmc_o1 .
./kmc -k20 -fa -ci1 in2.fasta kmc_o2 .
./kmc -k20 -fa -ci1 in3.fasta kmc_o3 . 
```


You may check the counted k-mers with ```./kmc_tools dump```:
```
./kmc_tools dump kmc_o1 kmc_o1.dump
./kmc_tools dump kmc_o2 kmc_o2.dump
./kmc_tools dump kmc_o3 kmc_o3.dump 
```
kmc_o1.dump:
```
AAAAAAAAAAAAAAAAAAAA	1
AAAAAAAAAAAAAAAAAAAC	1 
```
kmc_o2.dump:
```
AAAAAAAAAAAAAAAAAAAA	3
AAAAAAAAAAAAAAAAAAAG	1 
```
kmc_o3.dump:
```
AAAAAAAAAAAAAAAAAAAA	2
```

Now, lets say we want to make union of this three databases. 
**Step 2**. Define complex.op file:
```
INPUT:                                 
set1 = kmc_o1                     
set2 = kmc_o2                          
set3 = kmc_o3             
OUTPUT:                                
result = set3 + set1 + set2 
```
As a result there is a kmc database ```result```.
To print output in text format (an union of three databases) you may use:
```
./kmc_tools -hp dump result /dev/stdout
```
The result is:
```
AAAAAAAAAAAAAAAAAAAA    6
AAAAAAAAAAAAAAAAAAAC    1
AAAAAAAAAAAAAAAAAAAG    1
```

In the attachment, you may find the script (run.sh) to reproduce above results.

[complex.zip](https://github.com/refresh-bio/KMC/files/1870854/complex.zip)

I have also checked the example from kmc_tools help and it seems to work. Could you please send me your file that defines complex operations? I will try to reproduce behavior you described and handle it in kmc_tools to produce some more user friendly error message.

**Comment by notestaff** [comment]
@marekkokot The problem happens in the version of kmc_tools installed by bioconda, but not in the binary version you sent.
Can you tag a new release on github, so that I can try to update the bioconda recipe?
thanks,
ilya

**Comment by marekkokot** [comment]
I assume the problem was on bioconda side, if needed one can reopen this issue.
