### ISSUE TITLE
for read filtering, must read names be unique?

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#72]
@marekkokot Can you clarify, for kmc_tools filter, does it matter it two reads in the file have the same name?   (as in output from samtools fasta -n)

Maybe add this clarification to the docs.

**Comment by marekkokot** [comment]
@notestaff 
Read names are currently ignored by kmc_tools filter operation. Clarification was added to docs with 7aab256b8ce1e7611403af319c05d2e3c9d99868
