### ISSUE TITLE
python API

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#75]
Since much bioinfo work now happens in Python, it'd be great to have a Python wrapper around the kmc database API.

**Comment by hzpc-joostk** [comment]
Great suggestion. See also #48.

**Comment by marekkokot** [comment]
I have created some wrapper for KMC API, but I am not a python developer and I feel it could be done in a more pythonic way. Also as single API query is quite fast, and there are often many queries the performance of wrapped API in python is rather weak, so I am not convinced about its usability.
Wrapping some parts of KMC itself (as mentioned in #48) may be interesting, but is rather not trivial, as the level of KMC modularity seems to be not good enough, so, for now, we will probably do not try to wrap KMC functions in python. 

Anyway, I am closing this issue, if anything is not working correctly, or there are some suggestions on how to improve python API please create a new issue.
