### ISSUE TITLE
bug report -- segfault

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#85]
touch empty.fasta
kmc -v -fm -k1 -ci1 -cx2147483647 -cs255 -m1 -t1 -sm empty.fasta nokmers /tmp
kmc_tools -v -t1 transform nokmers -ci1 -cx2147483647 dump -s  mylist.txt
in1: 0% Segmentation fault

@marekkokot

**Comment by marekkokot** [comment]
It seems it have been fixed with 981e2fd534f8df2da5a782159e09811656bb8dd2
