### ISSUE TITLE
bug report - filtering empty database

### ISSUE THREAD

**Issue by notestaff** [refresh-bio/KMC#86]
(master_env_v12) [17:52] /tmp $ rm empty*
(master_env_v12) [17:52] /tmp $ touch empty.fasta
(master_env_v12) [17:52] /tmp $ kmc -fm empty.fasta empty_db /tmp
**
Stage 1: 100%
Stage 2: 100%
1st stage: 0.17806s
2nd stage: 0.075664s
Total    : 0.253724s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :            0
   No. of unique counted k-mers       :            0
   Total no. of k-mers                :            0
   Total no. of sequences             :            0
   Total no. of super-k-mers          :            0
(master_env_v12) [17:52] /tmp $ kmc_tools filter empty_db empty.fasta -fa empty_filtered.fasta
Error: cannot open: empty_db by KMC API

(this case does arise in practice) @marekkokot

**Comment by notestaff** [comment]
should be fixed by https://github.com/refresh-bio/KMC/pull/91

"empty kmer db" might seem trivial but does arise in practice, e.g. in some of our pipelines if an earlier step fails later steps see empty inputs, but we need the pipeline to still run without crashes.

**Comment by marekkokot** [comment]
@notestaff 
Hi, thanks for PR. 
I made it a little different, to be able to detect additionally situation when not enough bytes have been read from the file.
